name: tox

on: [push]

jobs:
  tox:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run tests
        run: make test
